### ISSUE TITLE
Fixing sampling module in vatf_executor

### ISSUE THREAD

**Issue by Mamatu** [Mamatu/vatf_executor#9]
Lack of adjust to log/system timezone should be fixed

```
Traceback (most recent call last):
  File "vatf_executor/main.py", line 49, in <module>
    module.main(args)
  File "/tmp/test/Test_One_Question/vatf_executor/sampling.py", line 128, in main
    config = config.Config("config.json")
AttributeError: 'NoneType' object has no attribute 'Config'
```

```
INFO:root:OutputToSave: ./samples/session_0/ into /tmp/tmp0llwf4mc
Traceback (most recent call last):
  File "vatf_executor/main.py", line 49, in <module>
    module.main(args)
  File "/tmp/test/Test_One_Question/vatf_executor/sampling.py", line 127, in main
    _checks_args(args)
  File "/tmp/test/Test_One_Question/vatf_executor/sampling.py", line 120, in _checks_args
    mandatory("args.path_to_log", args.path_to_log)
  File "/tmp/test/Test_One_Question/vatf_executor/sampling.py", line 116, in mandatory
    raise Exception("Mandatory {arg} doesn't exist")
Exception: Mandatory {arg} doesn't exist
/tmp/tf_0.pid
SIGINT
```

**Comment by Mamatu** [comment]
https://github.com/Mamatu/vatf_executor/pull/10

**Comment by Mamatu** [comment]
Related to:
https://github.com/Mamatu/vatf_generator/issues/5
https://github.com/Mamatu/vatf_utils/issues/8
